version: '3'
services:
  # The nginx proxy
  nginx:
    restart: always
    image: nginx:1.21.1
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./custom.conf:/etc/nginx/conf.d/custom.conf:ro
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen


  # The docker-gen to generate nginx config
  nginx-gen:
    restart: always
    build:
      context: .
    container_name: nginx-gen
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./custom.conf:/etc/nginx/conf.d/custom.conf:ro
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    depends_on:
      - nginx

  # Let's Encrypt
  nginx-letsencrypt:
    restart: always
    image: nginxproxy/acme-companion:2.1.0
    container_name: nginx-letsencrypt
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./custom.conf:/etc/nginx/conf.d/custom.conf:ro
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:rw
      - ./nginx/acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - NGINX_PROXY_CONTAINER=nginx
    depends_on:
      - nginx-gen

networks:
  default:
    external:
      name: nginx-proxy-network